# Generated by Django 3.2.17 on 2023-02-11 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('post_type', models.CharField(max_length=100)),
                ('game_filter', models.CharField(choices=[('pokemon_scarlet', 'Pokémon Scarlet'), ('pokemon_violet', 'Pokémon Violet'), ('pokemon_arceus', 'Pokémon Legends: Arceus'), ('pokemon_bd', 'Pokémon Brilliant Diamond'), ('pokemon_sp', 'Pokémon Shining Pearl'), ('pokemon_sword', 'Pokémon Sword'), ('pokemon_shield', 'Pokémon Shield'), ('pokemon_lets_go_eevee', 'Pokémon Lets Go Eeevee'), ('pokemon_lets_go_pikachu', 'Pokémon Lets Go Pikachu'), ('pokemon_go', 'Pokémon GO'), ('other', 'Other')], default='', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basepost')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('ingame_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('posts.basepost',),
        ),
        migrations.CreateModel(
            name='PokemonBuild',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.basepost')),
                ('move_one', models.CharField(max_length=100)),
                ('move_two', models.CharField(max_length=100)),
                ('move_three', models.CharField(max_length=100)),
                ('move_four', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('ev_stats', multiselectfield.db.fields.MultiSelectField(choices=[('hp', 'HP'), ('attack', 'Attack'), ('defense', 'Defense'), ('special_attack', 'Special Attack'), ('special_defense', 'Special Defense'), ('speed', 'Speed')], default='', max_length=100)),
                ('held_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.helditem')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.nature')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_caught', to='pokemons.caughtpokemon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('posts.basepost',),
        ),
    ]
