# Generated by Django 3.2.17 on 2023-02-09 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('ingame_name', models.CharField(blank=True, max_length=255)),
                ('game_filter', models.CharField(choices=[('pokemon_scarlet', 'Pokémon Scarlet'), ('pokemon_violet', 'Pokémon Violet'), ('pokemon_arceus', 'Pokémon Legends: Arceus'), ('pokemon_bd', 'Pokémon Brilliant Diamond'), ('pokemon_sp', 'Pokémon Shining Pearl'), ('pokemon_sword', 'Pokémon Sword'), ('pokemon_shield', 'Pokémon Shield'), ('pokemon_lets_go_eevee', 'Pokémon Lets Go Eeevee'), ('pokemon_lets_go_pikachu', 'Pokémon Lets Go Pikachu'), ('pokemon_go', 'Pokémon GO'), ('other', 'Other')], default='', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
