# Generated by Django 3.2.17 on 2023-02-09 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_caughtpokemon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonBuildPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_one', models.CharField(max_length=100)),
                ('move_two', models.CharField(max_length=100)),
                ('move_three', models.CharField(max_length=100)),
                ('move_four', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('ev_stats', models.CharField(choices=[('hp', 'HP'), ('attack', 'Attack'), ('defense', 'Defense'), ('special_attack', 'Special Attack'), ('special_defense', 'Special Defense'), ('speed', 'Speed')], default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_filter', models.CharField(choices=[('pokemon_scarlet', 'Pokémon Scarlet'), ('pokemon_violet', 'Pokémon Violet'), ('pokemon_arceus', 'Pokémon Legends: Arceus'), ('pokemon_bd', 'Pokémon Brilliant Diamond'), ('pokemon_sp', 'Pokémon Shining Pearl'), ('pokemon_sword', 'Pokémon Sword'), ('pokemon_shield', 'Pokémon Shield'), ('pokemon_lets_go_eevee', 'Pokémon Lets Go Eeevee'), ('pokemon_lets_go_pikachu', 'Pokémon Lets Go Pikachu'), ('pokemon_go', 'Pokémon GO'), ('other', 'Other')], default='', max_length=32)),
                ('held_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.helditem')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.nature')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons_caught', to='pokemons.caughtpokemon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
