# Generated by Django 3.2.17 on 2024-09-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepost',
            options={'ordering': ['-created_at']},
        ),
    ]
