# Generated by Django 3.2.17 on 2023-02-10 07:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_pokemonbuildpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonbuildpost',
            name='ev_stats',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hp', 'HP'), ('attack', 'Attack'), ('defense', 'Defense'), ('special_attack', 'Special Attack'), ('special_defense', 'Special Defense'), ('speed', 'Speed')], default='', max_length=100),
        ),
    ]
