# Generated by Django 3.2.17 on 2023-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='avatar',
            field=models.ImageField(default='../mew_avatar_g0pjd7', upload_to='profile_avatars/'),
        ),
    ]
